version: '3.7'

services:
  app:
    build:
      context: .
    environment:
      NODE_PATH: src
      # need to use different config paths for container
      NODE_ENV: docker
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./tmp
        target: /tanuki
