version: '3.7'

services:
  app:
    build:
      context: .
    environment:
      DB_PATH: /database
      UPLOAD_PATH: /uploads
      ASSETS_PATH: /blobstore
      PORT: 3000
      RUST_LOG: "info"
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./tmp/blobs
        target: /blobstore
      - type: bind
        source: ./tmp/rocksdb
        target: /database
      - type: bind
        source: ./tmp/uploads
        target: /uploads
