version: '3.7'

services:
  app:
    build:
      context: .
    environment:
      DATABASE_PATH: /database
      DATABASE_TYPE: rocksdb
      UPLOAD_PATH: /assets/uploads
      ASSETS_PATH: /assets/blobstore
      PORT: 3000
      RUST_LOG: "info"
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./tmp/docker/assets
        target: /assets
      - type: bind
        source: ./tmp/docker/database
        target: /database
