name: tanuki_server
description: Backend of digital asset management system.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  angel_cors: ^2.0.0
  angel_framework: ^2.1.1
  angel_graphql: ^2.0.0-beta
  angel_static: ^2.1.3+2
  exifdart: ^0.7.0+3
  file: ^5.1.0
  http_parser: ^3.1.3
  image: ^2.1.4
  logging: ^0.11.4
  mime: ^0.9.6+3
  pretty_logging: ^1.0.0

dev_dependencies:
  angel_test: ^2.0.1
  pedantic: ^1.8.0
  test: ^1.6.0
