//
// Copyright (c) 2025 Nathan Fiedler
//
import assert from 'node:assert';
import { type RecordRepository } from 'tanuki/server/domain/repositories/RecordRepository.ts';

export default ({ recordRepository }: { recordRepository: RecordRepository; }) => {
  assert.ok(recordRepository, 'record repository must be defined');
  /**
   * Generator function that yields all asset records in a format suitable for
   * loading back into the database using the `LoadAssets` use case.
   * 
   * @param batchSize - number of assets to fetch from database on each iteration.
   * @returns Promise that yields one asset record at a time.
   */
  return async function* (batchSize: number) {
    let cursor = null;
    while (true) {
      const [assets, next] = await recordRepository.fetchAssets(cursor, batchSize);
      for (const entry of assets) {
        // Convert the Asset entity into the dump file format generated by
        // previous versions of the application, including fields that are not
        // used by this version.
        let location: unknown = null;
        // Location gets special treatment in which those with only a label are
        // written out as just a string and not as a record of multiple fields.
        if (entry.location !== null) {
          if (entry.location.label !== null && entry.location.city === null && entry.location.region === null) {
            location = entry.location.label;
          } else {
            location = { l: entry.location.label, c: entry.location.city, r: entry.location.region };
          }
        }
        yield {
          key: entry.key,
          checksum: entry.checksum,
          filename: entry.filename,
          byte_length: entry.byteLength,
          media_type: entry.mediaType,
          tags: entry.tags,
          import_date: entry.importDate,
          caption: entry.caption,
          location,
          user_date: entry.userDate,
          original_date: entry.originalDate,
          dimensions: null,
        };
      }
      if (assets.length === 0) {
        break;
      }
      cursor = next;
    }
  };
};
